### ISSUE TITLE
Cannot find MuseScore on Windows even with “.Renviron” altered

### ISSUE THREAD

**Issue by arthurwelle** [flujoo/gm#1]
Hi there, It seems a nice work that you have done! I´m trying to use it on a Windows machine. I did follow the tutorial and tried several forms, but R cannot find MuseScore (I used the program normally after installation). 
 
Error: MuseScore must be installed to convert Music object to score or audio file.

I edited the “.Renviron” as suggested. It was the default path anyway "C:\Program Files\MuseScore 3\bin". 

I tried a) "C:\Program Files\MuseScore 3\bin\", 
b) "C:/Program Files/MuseScore 3/bin/" and 
c) "C:%\Program Files%\MuseScore%3%\bin%\"

Any suggestion?
Thanks!

**Comment by jake-wittman** [comment]
I also had this error and am on a Windows 10 computer. I installed normally with the default path. After some troubleshooting, I figured out you have to point the MUSESCORE_PATH to the executable MuseScore3 file. In my case this was "C:/Program Files/MuseScore 3/bin/MuseScore3.exe"

If I can figure out how to do a pull request, I'll suggest a change to the documentation that makes this a bit clearer that you have to point it to the executable file.

**Comment by arthurwelle** [comment]
Thank you Jacob! It worked! I coudn´t realise this on my own! The documentation could be improved for the slow, like myself, lol. Its only the infancy of the package, awesome work from the start!!

**Comment by flujoo** [comment]
I set a wrong default path for Windows system. I will fix this soon, and elaborate the documentation.

@arthurwelle Thank you for you pointing this out and your appreciation!
@wittja01 Thank you for your pull request! I will take your kind suggestion, but since I will modify both the code and documentation, I will not merge it directly.
