### ISSUE TITLE
Adding text to a score

### ISSUE THREAD

**Issue by tuomaseerola** [flujoo/gm#11]
I wonder whether it would be possible to add a text label to a score (title, lyric, expression, or label). This could be handy in some cases but there might be other workarounds beyond gm.

**Comment by flujoo** [comment]
@tuomaseerola gm can't do this currently, but I plan to improve gm's notation functionality including adding text, instrument, dynamics, ... in the following versions.

**Comment by tuomaseerola** [comment]
Thanks. Not essential, but as the GM capabilities grow, it is good to know that these are on the pipeline.

**Comment by sebsilas** [comment]
I second that this would be a very useful feature! Thank you for this great package.

**Comment by flujoo** [comment]
Thanks @sebsilas ! I am still working on the second version with which you can add texts and other components. Hope I will publish that this year.
