### ISSUE TITLE
show(m, to = c("audio","score")) results in Error: rsession-arm64: NegativeOrZeroImageSize `' @ error/image.c/CloneImage/795

### ISSUE THREAD

**Issue by markariosd3** [flujoo/gm#15]
I'm trying to run `show(m, to = c("audio","score"))` from the [Quick Example](https://cran.r-project.org/web/packages/gm/vignettes/gm.html#quick-example) but it gives the error `Error: rsession-arm64: NegativeOrZeroImageSize `' @ error/image.c/CloneImage/795`. Are there any suggestions you can kindly recommend for getting past this error?

**What I've Tried Thus Far**

 1. I searched for this error and it's related to the magick library. So I then tested it to make sure it's working and it does. 
 
 2. I read that .Renviron needs `MUSESCORE_PATH=/Applications/MuseScore 4.app` and usethis::edit_r_environ() to verify that it's there.
 
 3. I tried running `show(m, to = c("audio")) and in the Rstudio view is just renders a media ui that's not playable, i.e. you can not click play to hear the "C5".
 
 4. I tried running `show(m)` and it results in the same error mentioned in the title.
 
 5. I checked that MuseScore 4 is working by exporting a score in svg.
 
 6. I tried checking that all the dependencies are installed with `tools::package_dependencies("gm")`. 

**System Details**
Computer: Macbook Air
Memory: 8GB
Chip: Apple M1
Sonoma 14.2.1
git version 2.39.3 (Apple Git-146)
Homebrew 4.2.16
/opt/brew/opt/pkg-config (appears installed here)
Rstudio: Version 2023.03.1+446 (2023.03.1+446)
R version 4.3.3
gm version 1.0.2

**Console Details**
`
> library(gm)
> 
> m <- Music()
> 
> m <- m +
+   Meter(4,4) +
+   Line(pitches = list("C5"), durations = list("whole"))
> show(m, to = c("audio","score"))
Error: rsession-arm64: NegativeOrZeroImageSize `' @ error/image.c/CloneImage/795
`

**Comment by flujoo** [comment]
Hi @markariosd3, thanks for your feedback! I just tried the following path and it worked:

```
MUSESCORE_PATH=/Applications/MuseScore 4.app/Contents/MacOS/mscore
```

Hope this will help.

**Comment by markariosd3** [comment]
Works! Thanks so much!
Best,
Mark
