### ISSUE TITLE
R-Music inclusion

### ISSUE THREAD

**Issue by brunaw** [flujoo/gm#3]
Thanks for your message via the R-Music blog, this package is pretty cool! How would you like me to include it in R-Music, are you willing to 'transfer the repository to our GitHub organization https://r-music.rbind.io/ and/or write a blog post about it (for the R-Music blog)?

**Comment by flujoo** [comment]
@brunaw Thanks for your reply and appreciation! I would like to add [the vignette for this package](https://flujoo.github.io/gm/articles/gm.html) to R-Music blog, or write a new post If the vignette does not meet R-Music blog's requirements.

**Comment by brunaw** [comment]
@flujoo Sure, the vignette looks good for a blog post. Are you happy for me to change a few sentences here and there if needed? If yes I can add the vignette to the blog later this week

**Comment by flujoo** [comment]
@brunaw Sure, please feel free to make any changes.

**Comment by brunaw** [comment]
Here's the blog post: https://r-music.rbind.io/posts/2021-04-03-gm/ I also shared it on Twitter if you don't mind :)

**Comment by flujoo** [comment]
@brunaw It looks good! And of course not. Thanks for editing and sharing it.
