### ISSUE TITLE
other instruments ?

### ISSUE THREAD

**Issue by moodymudskipper** [flujoo/gm#4]
Thanks for this package, I had fun with it all evening.

Is it possible to hear another instrument than the piano ?
I have looked at all function arguments but haven't found a way.

If it's not possible as is, could you indicate me where this is set in the code so I can find a way to hack it for myself ?

**Comment by flujoo** [comment]
@moodymudskipper It's great you had fun!

This will be Implemented in the next minor version. If you still want to hack it:

1. <https://en.wikipedia.org/wiki/General_MIDI#Program_change_events> lists the MIDI numbers corresponding to the default instruments.

2. Make sure that you use the default virtual instruments library or SoundFont MuseScore_General.sf3. See <https://musescore.org/en/handbook/3/soundfonts-and-sfz-files>.

3. The related MusicXML element:

```xml
<score-part id="P1">
  <part-name>Piccolo</part-name>
  <part-abbreviation>Picc.</part-abbreviation>
  <score-instrument id="P1-I1">
    <instrument-name></instrument-name>
  </score-instrument>
  <midi-device id="P1-I1" port="1"></midi-device>
  <midi-instrument id="P1-I1">
    <midi-channel>1</midi-channel>
    <midi-program>1</midi-program>
    <volume>78.7402</volume>
    <pan>0</pan>
  </midi-instrument>
</score-part>
```

In the MusicXML file, each part has it own `score-part` element, you can change the MIDI number in `<midi-program>1</midi-program>` to change its instrument. In my experience with MuseScore, `<instrument-name></instrument-name>` should be empty.

4. In R/show.R,  you may want to hack `Score()` and `to_Score()` to add `$instruments` component, and in `to_Element.Score()` add some code to convert `$instruments` to internal `Element` object (see Element.R), which is used to represent MusicXML.

**Comment by moodymudskipper** [comment]
Many thanks for the fast and detailed answer, I will give it a go!
